"""
LangChain agent for processing Telegram messages.
"""

import os
from typing import Any

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_ollama import ChatOllama

load_dotenv()


# Configure the LLM model
llm = ChatOllama(
    model="gpt-oss:120b-cloud",
    temperature=0.1,
)


# Define available tools for the agent
tools = []


# Create the agent
agent_executor = create_agent(
    llm,
    tools,
    system_prompt="""You are a smart and friendly Telegram assistant.

        Your task is to:
        1. Analyze messages from users
        2. Respond helpfully and conversationally
        3. Be polite, clear, and Very VERY concise in your responses

        Respond naturally and helpfully.""",
)


def process_telegram_message(user_id: str, message_text: str) -> str:
    """
    Process a Telegram message using the LangChain agent.

    Args:
        user_id: User's Telegram ID
        message_text: Received message text

    Returns:
        str: Response generated by the agent
    """
    try:
        # Invoke the agent with the message
        response = agent_executor.invoke(
            {
                "messages": [HumanMessage(content=message_text)],
            }
        )

        # Extract the response from the output
        if response and "messages" in response:
            last_message = response["messages"][-1]
            return (
                last_message.content
                if hasattr(last_message, "content")
                else str(last_message)
            )

        return "Sorry, I could not process your message."

    except Exception as e:
        print(f"❌ Error processing message with agent: {e}")
        return f"There was an error processing your message: {str(e)}"
