"""
LangChain agent for processing WhatsApp messages.
"""

import os
from typing import Any

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from tools import send_whatsapp_message

load_dotenv()


# Configure the LLM model
llm = ChatOpenAI(
    model="gpt-4o-mini", temperature=0.7, api_key=os.getenv("OPENAI_API_KEY")
)


# Define available tools for the agent
tools = [send_whatsapp_message]


# Create the agent
agent_executor = create_agent(
    llm,
    tools,
    messages_modifier="""You are a smart and friendly WhatsApp assistant.

Your task is to:
1. Analyze messages from users
2. Respond helpfully and conversationally
3. When you need to start a conversation or send a message to someone, use the send_whatsapp_message tool
4. Be polite, clear, and concise in your responses

Respond naturally and helpfully.""",
)


def process_whatsapp_message(sender_number: str, message_text: str) -> str:
    """
    Process a WhatsApp message using the LangChain agent.

    Args:
        sender_number: Sender's phone number
        message_text: Received message text

    Returns:
        str: Response generated by the agent
    """
    try:
        # Invoke the agent with the message
        response = agent_executor.invoke(
            {
                "messages": [HumanMessage(content=message_text)],
            }
        )

        # Extract the response from the output
        if response and "messages" in response:
            last_message = response["messages"][-1]
            return (
                last_message.content
                if hasattr(last_message, "content")
                else str(last_message)
            )

        return "Sorry, I could not process your message."

    except Exception as e:
        print(f"❌ Error processing message with agent: {e}")
        return f"There was an error processing your message: {str(e)}"
